name: Release Webhook Trigger

on:
  release:
    types: [published]

jobs:
  trigger-webhook:
    runs-on: self-hosted

    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Activar webhook
        env:
          SERVER_URL: "http://localhost:3000/github-webhook"
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -d '{"action": "published", "repository": {"html_url": "https://github.com/${{ github.repository }}"}, "release": {"tag_name": "${{ github.event.release.tag_name }}"}}' \
               $SERVER_URL
