name: Release Webhook Trigger

on:
  release:
    types: [published]

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Instalar curl
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      # Paso 2: Ejecutar el script para realizar la solicitud
      - name: Trigger webhook on release
        env:
          SERVER_URL: "http://localhost:3000/github-webhook" # URL de tu servidor Express
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -d '{"action": "published", "repository": {"html_url": "https://github.com/${{ github.repository }}"}, "release": {"tag_name": "${{ github.event.release.tag_name }}"}}' \
               $SERVER_URL
