name: Release Webhook Trigger

on:
  release:
    types: [published]

jobs:
  trigger-webhook:
    runs-on: self-hosted

    steps:
      - name: Descargar release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SERVER_URL: "http://localhost:3000/descargar_assets"
        run: |
          # Obtener el ID del release
          $release_id = ${{ github.event.release.id }}
          $assets_url = "https://api.github.com/repos/${{ github.repository }}/releases/$release_id/assets"
          

          $headers = @{
            Authorization = "Bearer $env:GITHUB_TOKEN"
            Accept        = "application/vnd.github.v3+json"
          }

          # Obtener la lista de Assets
          Write-Host "Obteniendo los Assets del release desde: $assets_url"
          $assets = Invoke-RestMethod -Uri $assets_url -Headers $headers -Method Get

          # Filtrar los archivos .txt
          $hexFiles = $assets | Where-Object { $_.name -like "*.txt" }
          if (-not $hexFiles) {
              Write-Host "No se encontraron archivos .hex. Finalizando."
              exit 0
          }
          $downloadUrls = $hexFiles | ForEach-Object { $_.browser_download_url }
          Write-Host $downloadUrls
          $body = @{
              nombre = "${{ github.event.release.name }}"
              urls = $downloadUrls
              repositorio = @{"https://github.com/${{ github.repository }}"}
          }
          Invoke-RestMethod -Uri $env:SERVER_URL -Method Post -Body ($body | ConvertTo-Json -Depth 10) -ContentType "application/json"
