name: Release Webhook Trigger

on:
  release:
    types: [published]

jobs:
  trigger-webhook:
    runs-on: self-hosted

    steps:
      - name: Descargar release
        env:
          FRAPPE_TOKEN: ${{ secrets.TOKEN }}
          SERVER_URL: ${{ secrets.URL }}
        run: |
          $assets = '${{ toJson(github.event.release.assets) }}'
          Write-Host $assets
          $hexFiles = $assets | ConvertFrom-Json | Where-Object { $_.name -like "*.hex" }
          if (-not $hexFiles) {
              Write-Host "No se encontraron archivos .hex. Finalizando."
              exit 0
          }
          $downloadUrls = $hexFiles | ForEach-Object { $_.browser_download_url }
          Write-Host $downloadUrls
          $headers = @{
            Authorization = "token $env:FRAPPE_TOKEN"
          }
          $body = @{
              nombre = "${{ github.event.release.name }}"
              urls = $downloadUrls
              text = "${{ github.event.release.body }}"
              repositorio = "https://github.com/${{ github.repository }}"
          }
          Invoke-RestMethod -Uri $env:SERVER_URL -Method Post -Headers $headers -Body ($body | ConvertTo-Json -Depth 10) -ContentType "application/json"
